spring:
  application:
    name: demo
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/shops
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update